import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import { AuthContextProvider } from '@/contexts/AuthContext'
import { Inter } from 'next/font/google'



const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="" lang="en" >
      <body className={inter.className}>
        <AuthContextProvider> 
          {children}
          <Toaster />
        </AuthContextProvider>
      </body>
    </html>
  );
}
